"""Function-oriented synthetic H-alpha solar-filament forward model."""

from .analysis import (
    extract_time_distance,
    fit_damped_sine,
    measure_static_cohesion,
    padded_mask_bounds,
    track_dark_band,
)
from .config import (
    GONG_DISK_RADIUS_PX,
    GONG_OVERSAMPLE,
    GONG_PIXEL_KM,
    SOLAR_RADIUS_KM,
    make_static_config,
    opacity_temperature_domain_K,
    update_static_config,
    validate_static_config,
)
from .degradation import degrade_transmission
from .dynamic_background import (
    DEFAULT_H5_DYNAMICS_PATH,
    load_h5_background_sequence,
)
from .dynamics import (
    current_dynamics_frame,
    dynamics_background_at_frame,
    initialize_dynamics,
    make_dynamics_config,
    simulate_filament_dynamics,
    step_dynamics,
)
from .experiment_config import (
    DEFAULT_EXPERIMENT_CONFIG_PATH,
    DEFAULT_EXPERIMENTS_ROOT,
    clone_simulation_as_experiment,
    create_experiment,
    experiment_config_sha256,
    list_experiments,
    list_standalone_simulations,
    load_experiment_config,
    next_background_seed,
    next_experiment_seeds,
    normalize_experiment_config,
    save_experiment_config,
    static_preview_fingerprint,
    static_preview_fingerprint_payload,
    validate_experiment_config,
    validate_preview_config,
    validate_production_config,
    validate_save_config,
)
from .experiment_runner import (
    generate_experiment_preview,
    list_jobs,
    load_preview,
    preview_is_current,
    start_experiment_worker,
)
from .generator import (
    assign_static_plasma,
    generate_from_h5_background,
    generate_static_filament,
    generate_static_geometry,
    make_h5_static_config,
    render_static_state,
)
from .io import STATIC_OUTPUT_SCHEMA_VERSION, load_static_result, save_static_result
from .opacity_table import (
    HEINZEL_EXTENSION_FILENAME,
    HEINZEL_EXTENSION_SHA256,
    heinzel_opacity_table_metadata,
    load_heinzel_opacity_table,
)
from .oscillation import (
    OSCILLATION_MODE_LUNA_2022,
    OSCILLATION_MODE_SHARED_PERIOD,
    SOLAR_RADIUS_M,
    SOLAR_SURFACE_GRAVITY_KM_S2,
    SOLAR_SURFACE_GRAVITY_M_S2,
    equivalent_curvature_radius_m,
    gravity_cutoff_period_s,
    luna_2022_inferred_curvature_radius_m,
    luna_2022_longitudinal_period_s,
    solar_gravity_m_s2,
)
from .render import compose_transmission, dilute_transmission
from .simulation_io import (
    DEFAULT_SIMULATIONS_ROOT,
    SIMULATION_DATASET_SCHEMA_VERSION,
    abort_simulation,
    finalize_simulation,
    make_export_config,
    open_simulation_recorder,
    rebuild_simulation_index,
    simulate_and_save_filament_dynamics,
    write_simulation_frame,
)
from .video import save_gong_video, save_velocity_video
from .visualization import save_static_summary

__all__ = [
    "DEFAULT_H5_DYNAMICS_PATH",
    "DEFAULT_EXPERIMENT_CONFIG_PATH",
    "DEFAULT_EXPERIMENTS_ROOT",
    "DEFAULT_SIMULATIONS_ROOT",
    "GONG_DISK_RADIUS_PX",
    "GONG_OVERSAMPLE",
    "GONG_PIXEL_KM",
    "HEINZEL_EXTENSION_FILENAME",
    "HEINZEL_EXTENSION_SHA256",
    "OSCILLATION_MODE_LUNA_2022",
    "OSCILLATION_MODE_SHARED_PERIOD",
    "SIMULATION_DATASET_SCHEMA_VERSION",
    "STATIC_OUTPUT_SCHEMA_VERSION",
    "SOLAR_RADIUS_M",
    "SOLAR_RADIUS_KM",
    "SOLAR_SURFACE_GRAVITY_KM_S2",
    "SOLAR_SURFACE_GRAVITY_M_S2",
    "abort_simulation",
    "assign_static_plasma",
    "clone_simulation_as_experiment",
    "compose_transmission",
    "create_experiment",
    "current_dynamics_frame",
    "degrade_transmission",
    "dilute_transmission",
    "dynamics_background_at_frame",
    "equivalent_curvature_radius_m",
    "extract_time_distance",
    "experiment_config_sha256",
    "finalize_simulation",
    "fit_damped_sine",
    "generate_from_h5_background",
    "generate_static_filament",
    "generate_static_geometry",
    "generate_experiment_preview",
    "gravity_cutoff_period_s",
    "heinzel_opacity_table_metadata",
    "initialize_dynamics",
    "list_experiments",
    "list_jobs",
    "list_standalone_simulations",
    "load_experiment_config",
    "load_h5_background_sequence",
    "load_heinzel_opacity_table",
    "load_preview",
    "load_static_result",
    "luna_2022_inferred_curvature_radius_m",
    "luna_2022_longitudinal_period_s",
    "make_dynamics_config",
    "make_export_config",
    "make_h5_static_config",
    "make_static_config",
    "measure_static_cohesion",
    "open_simulation_recorder",
    "next_background_seed",
    "next_experiment_seeds",
    "normalize_experiment_config",
    "opacity_temperature_domain_K",
    "padded_mask_bounds",
    "rebuild_simulation_index",
    "render_static_state",
    "preview_is_current",
    "save_static_result",
    "save_static_summary",
    "save_gong_video",
    "save_experiment_config",
    "save_velocity_video",
    "static_preview_fingerprint",
    "static_preview_fingerprint_payload",
    "simulate_and_save_filament_dynamics",
    "simulate_filament_dynamics",
    "solar_gravity_m_s2",
    "step_dynamics",
    "start_experiment_worker",
    "track_dark_band",
    "update_static_config",
    "validate_static_config",
    "validate_experiment_config",
    "validate_preview_config",
    "validate_production_config",
    "validate_save_config",
    "write_simulation_frame",
]
